import './globals.css'
import { Quicksand } from 'next/font/google'
import { NoteProvider } from './context/NoteContext'
import Nav from './components/Nav';
import SideNav from './components/SideNav';

const quicksand = Quicksand({ subsets: ['latin'] });

export const metadata = {
  title: 'Google Keep Clone',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={quicksand.className} lang="en">
      <body className="bg-gray-800 scrollbar-hidden">
        <NoteProvider>
          <Nav/>
          <div className='h-screen w-full'>
            <SideNav/>
            {children}
          </div>
        </NoteProvider>
      </body>
    </html>
  ) 
}
